server:
  port: 8080

spring:
  application:
    name: nequi-franquicias

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
